# Must set
# + $GITHUB_TOKEN

os: linux
dist: xenial

# Do not choose a language; we provide our own build tools.
language: node_js

# Caching so the next build will be fast too.
cache:
  directories:
    - "node_modules"

# Ensure necessary system libraries are present
node_js:
  - "lts/*"

script:
  - npm test
  - npm run build

deploy:
  # Deploy updated docs to github pages
  provider: pages:git
  edge: true
  token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  target-branch: master
  local_dir: public
  deployment_file: false
  cleanup: false
  on:
    branch: production
